[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "smc_bot"
version = "0.0.1"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where  = ["."]
include = ["core","data","backtest","trade","gui"]
